# https://www.appveyor.com/docs/appveyor-yml/

version: '{build}'
shallow_clone: true
build: off

image:
  - Visual Studio 2019

environment:
  matrix:
    - perl_type: strawberry
      perl_version: 5.32.0.1    #gcc 8.3.0
      perl_bits: 32
    - perl_type: strawberry
      perl_version: 5.32.0.1    #gcc 8.3.0
      perl_bits: 64
    - perl_type: strawberry
      perl_version: 5.30.3.1    #gcc 8.3.0
      perl_bits: 32
    - perl_type: strawberry
      perl_version: 5.30.3.1    #gcc 8.3.0
      perl_bits: 64
    - perl_type: strawberry     #gcc 7.1.0
      perl_version: 5.28.2.1
      perl_bits: 32
    - perl_type: strawberry     #gcc 7.1.0
      perl_version: 5.28.2.1
      perl_bits: 64
#    - perl_type: strawberry
#      perl_version: 5.26.3.1    #gcc 7.1.0
#      perl_bits: 32
#    - perl_type: strawberry
#      perl_version: 5.26.3.1    #gcc 7.1.0
#      perl_bits: 64
    - perl_type: strawberry
      perl_version: 5.24.4.1    #gcc 4.9.2
      perl_bits: 32
    - perl_type: strawberry
      perl_version: 5.24.4.1    #gcc 4.9.2
      perl_bits: 64
#    - perl_type: strawberry
#      perl_version: 5.22.3.1    #gcc 4.9.2
#      perl_bits: 32
#    - perl_type: strawberry
#      perl_version: 5.22.3.1    #gcc 4.9.2
#      perl_bits: 64
#    - perl_type: strawberry
#      perl_version: 5.20.3.3    #gcc 4.8.3
#      perl_bits: 32
#    - perl_type: strawberry
#      perl_version: 5.20.3.3    #gcc 4.8.3
#      perl_bits: 64
#    - perl_type: strawberry
#      perl_version: 5.18.4.1    #gcc 4.7.3
#      perl_bits: 32
#    - perl_type: strawberry
#      perl_version: 5.18.4.1    #gcc 4.7.3
#      perl_bits: 64
#    - perl_type: strawberry
#      perl_version: 5.16.3.1    #gcc 4.6.3
#      perl_bits: 32
#    - perl_type: strawberry     #gcc 4.6.3
#      perl_version: 5.16.3.1
#      perl_bits: 64
    - perl_type: strawberry
      perl_version: 5.14.4.1    #gcc 4.6.3
      perl_bits: 32
    - perl_type: strawberry
      perl_version: 5.14.4.1    #gcc 4.6.3
      perl_bits: 64
#    - perl_type: strawberry_old
#      perl_version: 5.12.3.0    #gcc 4.4.3
#    - perl_type: strawberry_old
#      perl_version: 5.10.1.2    #gcc 3.4.5
#    - perl_type: cygwin64       #we already run cygwin tests via github actions
#    - perl_type: cygwin32       #stopped working

init:
  - reg add "HKLM\SYSTEM\CurrentControlSet\Control\Windows" /f /v ErrorMode /d 2
  - reg add "HKLM\Software\Microsoft\Windows\Windows Error Reporting" /f /v DontShowUI /d 1

install:
  - cinst -y wget
  - call .appveyor.cmd perl_setup
  - set MAKEFLAGS=-j4
  - set AUTHOR_MODE=0
  - '%perl% -V'
  - '%cpanm% --notest --installdeps --with-recommends .'

build_script:
  - '%perl% Makefile.PL'
  - '%make%'

test_script:
  - '%make% test'
