name: 01-main

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: perl:latest
    steps:
      - uses: actions/checkout@v4
      - name: perl -V
        run: perl -V
      - name: gcc -v
        run: gcc -v
      - name: Install dependencies
        run: |
          cpanm -n --installdeps .
      - name: Run build
        run: |
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 1
      - name: Run tests
        run: prove -j4 -b t
        env:
          AUTHOR_MODE: 1

  mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: curl --silent -L https://cpanmin.us | perl - --notest --installdeps .
      - name: Run build
        run: |
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 0
      - name: Run tests
        run: prove -j4 -b t
        env:
          AUTHOR_MODE: 0

  windows:
    runs-on: windows-latest
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v4
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm --installdeps .
      - name: Run build
        run: |
          perl Makefile.PL
          make -j4
        env:
          AUTHOR_MODE: 0
      - name: Run tests
        run: prove -j4 -b t
        env:
          AUTHOR_MODE: 0
